version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  adservice:
    build:
      context: ./src/adservice
    ports:
      - "9555:9555"
    environment:
      - PORT=9555
    networks:
      - app_network

  cartservice:
    build:
      context: ./src/cartservice/src
    ports:
      - "7070:7070"
    environment:
      - REDIS_ADDR=redis-cart:6379
    networks:
      - app_network

  checkoutservice:
    build:
      context: ./src/checkoutservice
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50052
      - EMAIL_SERVICE_ADDR=emailservice:5000
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shippingservice:50051
      - CART_SERVICE_ADDR=cartservice:7070
    networks:
      - app_network

  currencyservice:
    build:
      context: ./src/currencyservice
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - DISABLE_PROFILER=1
    networks:
      - app_network

  emailservice:
    build:
      context: ./src/emailservice
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1
    networks:
      - app_network

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "80:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8081
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shippingservice:50051
      - ENABLE_PROFILER=0
    networks:
      - app_network

  loadgenerator:
    build:
      context: ./src/loadgenerator
    environment:
      - FRONTEND_ADDR=frontend:80
      - USERS=10
    networks:
      - app_network

  paymentservice:
    build:
      context: ./src/paymentservice
    ports:
      - "50052:50052"
    environment:
      - PORT=50052
      - DISABLE_PROFILER=1
    networks:
      - app_network

  productcatalogservice:
    build:
      context: ./src/productcatalogservice
    ports:
      - "3550:3550"
    environment:
      - PORT=3550
      - DISABLE_PROFILER=1
    networks:
      - app_network

  recommendationservice:
    build:
      context: ./src/recommendationservice
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - DISABLE_PROFILER=1
    networks:
      - app_network

  redis-cart:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app_network

  shippingservice:
    build:
      context: ./src/shippingservice
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1
    networks:
      - app_network

volumes:
  redis-data: