
# frontend service

frontend:
  name: frontend
  image: santoshpalla27/online-botique:frontend
  ports:
    containerPort: 8080
  replicas: 1
  serviceAccountName: online-botique
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
     
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true    

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  livenessProbe:
    httpGet:
      path: "/_healthz"
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: "/_healthz"
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  env:
    - name: PORT
      value: "8080"

    - name: ENABLE_PROFILER
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: ENABLE_PROFILER

    - name: PRODUCT_CATALOG_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: PRODUCT_CATALOG_SERVICE_ADDR

    - name: CURRENCY_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: CURRENCY_SERVICE_ADDR

    - name: CART_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: CART_SERVICE_ADDR

    - name: RECOMMENDATION_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: RECOMMENDATION_SERVICE_ADDR

    - name: SHIPPING_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: SHIPPING_SERVICE_ADDR

    - name: CHECKOUT_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: CHECKOUT_SERVICE_ADDR

    - name: AD_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: AD_SERVICE_ADDR

    - name: SHOPPING_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: SHOPPING_SERVICE_ADDR

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  service:
    port: 80
    targetPort: 8080
    type: LoadBalancer

#adservice service

adservice:
  name: adservice
  serviceAccountName: online-botique
  image: santoshpalla27/online-botique:adservice
  replicas: 1
  ports:
    containerPort: 9555
  env: 
    name: PORT
    value: "9555"

  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  readinessProbe:
    grpc:
      port: 9555
    initialDelaySeconds: 5  
    periodSeconds: 10  
    failureThreshold: 3  
  livenessProbe:
    grpc:
      port: 9555
    initialDelaySeconds: 5  
    periodSeconds: 10  
    failureThreshold: 3

  service:
    port: 9555
    targetPort: 9555
    type: ClusterIP


# cartservice service

cartservice:
  name: cartservice
  serviceAccountName: online-botique
  image: santoshpalla27/online-botique:cartservice
  replicas: 1
  ports:
    containerPort: 7070

  readinessProbe:
    grpc:
      port: 7070
    initialDelaySeconds: 5  
    periodSeconds: 10  
    failureThreshold: 3  
  livenessProbe:
    grpc:
      port: 7070
    initialDelaySeconds: 5  
    periodSeconds: 10  
    failureThreshold: 3     
  
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true

    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  env:
    - name: REDIS_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: REDIS_ADDR

  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi


  service:
    port: 7070
    targetPort: 7070
    type: ClusterIP

# redis service      

redis:
  name: redis
  image: redis:alpine
  ports:
    containerPort: 6379
  replicas: 1
  serviceAccountName: online-botique

  readinessProbe:
    tcpSocket:
      port: 6379
    initialDelaySeconds: 5  
    periodSeconds: 10  
    failureThreshold: 3  
  livenessProbe:
    tcpSocket:
      port: 6379
    initialDelaySeconds: 5  
    periodSeconds: 10  
    failureThreshold: 3  

  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true

    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  volumeMounts:
    name: redis-data
    mountPath: /data
  
  volumes:
    name: redis-data
    persistentVolumeClaim:
      claimName: redis-pvc 

  service:
    name: redis-cart 
    port: 6379
    targetPort: 6379


  pv:
    name: redis-pv
    storage: 1Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain

  pvc:
    name: redis-pvc
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi


checkoutservice:
  name: checkoutservice
  serviceAccountName: online-botique
  image: santoshpalla27/online-botique:checkoutservice
  replicas: 1

  ports:
    containerPort: 5050

  readinessProbe:
    grpc:
      port: 5050
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  livenessProbe:
    grpc:
      port: 5050
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  env:
    - name: PORT
      value: "5050"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: PRODUCT_CATALOG_SERVICE_ADDR
    - name: SHIPPING_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: SHIPPING_SERVICE_ADDR
    - name: PAYMENT_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: PAYMENT_SERVICE_ADDR
    - name: EMAIL_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: EMAIL_SERVICE_ADDR
    - name: CURRENCY_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: CURRENCY_SERVICE_ADDR
    - name: SHOPPING_ASSISTANT_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: SHOPPING_ASSISTANT_SERVICE_ADDR
    - name: CART_SERVICE_ADDR
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: CART_SERVICE_ADDR

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  service:
    port: 5050
    type: ClusterIP


configmap:
  name: online-botique
  data:
    DISABLE_PROFILER: "1"
    ENABLE_PROFILER: "0"
    REDIS_ADDR: "redis-cart:6379"
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    SHIPPING_SERVICE_ADDR: "shippingservice:50051"
    PAYMENT_SERVICE_ADDR: "paymentservice:50052"
    EMAIL_SERVICE_ADDR: "emailservice:5000"
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"
    SHOPPING_ASSISTANT_SERVICE_ADDR: "shippingservice:50051"
    CART_SERVICE_ADDR: "cartservice:7070"
    RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8081"
    CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
    AD_SERVICE_ADDR: "adservice:9555"



currencyservice:
  name: currencyservice
  image: santoshpalla27/online-botique:currencyservice
  replicas: 1
  serviceAccountName: online-botique

  ports:
    containerPort: 7000

  readinessProbe:
    grpc:
      port: 7000
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  livenessProbe:
    grpc:
      port: 7000
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  env:
    PORT: "7000"
    DISABLE_PROFILER:
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: DISABLE_PROFILER

  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  service:
    port: 7000
    targetPort: 7000
    type: ClusterIP



emailservice:
  name: emailservice
  image: santoshpalla27/online-botique:emailservice
  replicas: 1
  serviceAccountName: online-botique

  ports:
    containerPort: 8080

  readinessProbe:
    grpc:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  livenessProbe:
    grpc:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  env:
    PORT: "8080"
    DISABLE_PROFILER:
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: DISABLE_PROFILER

  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  service:
    port: 5000
    targetPort: 8080
    type: ClusterIP



paymentservice:
  name: paymentservice
  image: santoshpalla27/online-botique:paymentservice
  replicas: 1
  serviceAccountName: online-botique

  ports:
    containerPort: 50052

  readinessProbe:
    grpc:
      port: 50052
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  livenessProbe:
    grpc:
      port: 50052
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  env:
    PORT: "50052"
    DISABLE_PROFILER:
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: DISABLE_PROFILER

  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  service:
    port: 50052
    targetPort: 50052
    type: ClusterIP




productcatalogservice:
  name: productcatalogservice
  image: santoshpalla27/online-botique:productcatalogservice
  replicas: 1
  serviceAccountName: online-botique

  ports:
    containerPort: 3550

  readinessProbe:
    grpc:
      port: 3550
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  livenessProbe:
    grpc:
      port: 3550
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  env:
    PORT: "3550"
    DISABLE_PROFILER:
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: DISABLE_PROFILER

  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  service:
    port: 3550
    targetPort: 3550
    type: ClusterIP



recommendationservice:
  name: recommendationservice
  image: santoshpalla27/online-botique:recommendationservice
  replicas: 1
  serviceAccountName: online-botique

  ports:
    containerPort: 8080

  readinessProbe:
    grpc:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  livenessProbe:
    grpc:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  env:
    PORT: "8080"
    DISABLE_PROFILER:
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: DISABLE_PROFILER
    PRODUCT_CATALOG_SERVICE_ADDR:
      valueFrom:
        configMapKeyRef:
          name: online-botique
          key: PRODUCT_CATALOG_SERVICE_ADDR

  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi

  service:
    port: 8081
    targetPort: 8080
    type: ClusterIP


namespace: default

serviceAccount:
  name: online-botique


shippingservice:
  name: shippingservice
  image: santoshpalla27/online-botique:shippingservice
  replicas: 1
  serviceAccountName: online-botique

  ports:
    containerPort: 50051

  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true

    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

  readinessProbe:
    grpc:
      port: 50051
    initialDelaySeconds: 5  
    periodSeconds: 10  
    failureThreshold: 3  

  livenessProbe:
    grpc:
      port: 50051
    initialDelaySeconds: 5  
    periodSeconds: 10  
    failureThreshold: 3
  
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  env:
      PORT: "50051"
      DISABLE_PROFILER:
        valueFrom:
          configMapKeyRef:
            name: online-botique
            key: DISABLE_PROFILER


  service: 
    port: 50051
    targetPort: 50051
    type: ClusterIP