apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: online-botique
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: adservice
        readinessProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 5  
          periodSeconds: 10  
          failureThreshold: 3  
        livenessProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 5  
          periodSeconds: 10  
          failureThreshold: 3  
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: santoshpalla27/online-botique:adservice
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"

---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  selector:
    app: adservice
  ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555
  type: ClusterIP
