apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: online-botique
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: currencyservice
        readinessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 5  
          periodSeconds: 10  
          failureThreshold: 3  
        livenessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 5  
          periodSeconds: 10  
          failureThreshold: 3  
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: santoshpalla27/online-botique:currencyservice
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: online-botique
              key: DISABLE_PROFILER
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  selector:
    app: currencyservice  
  ports:
    - protocol: TCP
      port: 7000  
      targetPort: 7000
  type: ClusterIP  
