apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      serviceAccountName: online-botique
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: emailservice
        readinessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 5  
          periodSeconds: 10  
          failureThreshold: 3  
        livenessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 5  
          periodSeconds: 10  
          failureThreshold: 3  
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: santoshpalla27/online-botique:emailservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: online-botique
              key: DISABLE_PROFILER
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  selector:
    app: emailservice  
  ports:
    - protocol: TCP
      port: 5000  
      targetPort: 8080
  type: ClusterIP  
