apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      serviceAccountName: online-botique
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: productcatalogservice
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
        image: santoshpalla27/online-botique:productcatalogservice
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: online-botique
              key: DISABLE_PROFILER
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  selector:
    app: productcatalogservice  
  ports:
    - protocol: TCP
      port: 3550  
      targetPort: 3550
  type: ClusterIP  
