apiVersion: v1
kind: ServiceAccount
metadata:
  name: online-botique
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: online-botique
  namespace: default
rules: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: online-botiquebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: online-botique
    namespace: default
roleRef:
  kind: Role
  name: online-botique
  apiGroup: rbac.authorization.k8s.io
