apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: online-botique
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: shippingservice
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5  
          periodSeconds: 10  
          failureThreshold: 3  
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5  
          periodSeconds: 10  
          failureThreshold: 3  
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: santoshpalla27/online-botique:shippingservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: online-botique
              key: DISABLE_PROFILER  
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi          
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  selector:
    app: shippingservice  
  ports:
    - protocol: TCP
      port: 50051  
      targetPort: 50051
  type: ClusterIP  
