apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shippingservice.name }}
spec:
  replicas: {{ .Values.shippingservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.shippingservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.shippingservice.name }}
    spec:
      serviceAccountName: {{ .Values.shippingservice.serviceAccountName }}
      securityContext:
        fsGroup: {{ .Values.shippingservice.securityContext.fsGroup }}
        runAsGroup: {{ .Values.shippingservice.securityContext.runAsGroup }}
        runAsUser: {{ .Values.shippingservice.securityContext.runAsUser }}
        runAsNonRoot: {{ .Values.shippingservice.securityContext.runAsNonRoot }}
      containers:
      - name: {{ .Values.shippingservice.name }}
        readinessProbe:
          grpc:
            port: {{ .Values.shippingservice.readinessProbe.grpc.port }}
          initialDelaySeconds: {{ .Values.shippingservice.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.shippingservice.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.shippingservice.readinessProbe.failureThreshold }}
        livenessProbe:
          grpc:
            port: {{ .Values.shippingservice.livenessProbe.grpc.port }}
          initialDelaySeconds: {{ .Values.shippingservice.livenessProbe.initialDelaySeconds }} 
          periodSeconds: {{ .Values.shippingservice.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.shippingservice.livenessProbe.failureThreshold }}  
        securityContext:
          allowPrivilegeEscalation: {{ .Values.shippingservice.securityContext.allowPrivilegeEscalation }}
          capabilities:
            drop:
              {{ toYaml .Values.shippingservice.securityContext.capabilities.drop }}
          privileged: {{ .Values.shippingservice.securityContext.privileged }}
          readOnlyRootFilesystem: {{ .Values.shippingservice.securityContext.readOnlyRootFilesystem }}
        image: {{ .Values.shippingservice.image }}
        ports:
        - containerPort: {{ .Values.shippingservice.containerPort }}
          name: grpc
        env:
        - name: PORT
          value: "{{ .Values.shippingservice.env.PORT }}"
        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.shippingservice.env.DISABLE_PROFILER.valueFrom.configMapKeyRef.name }}
              key: {{ .Values.shippingservice.env.DISABLE_PROFILER.valueFrom.configMapKeyRef.key }}
        resources:
          requests:
            cpu: {{ .Values.shippingservice.resources.requests.cpu }}
            memory: {{ .Values.shippingservice.resources.requests.memory }}
          limits:
            cpu: {{ .Values.shippingservice.resources.limits.cpu }}
            memory: {{ .Values.shippingservice.resources.limits.memory }}          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shippingservice.name }}
  labels:
    app: {{ .Values.shippingservice.name }}
spec:
  selector:
    app: {{ .Values.shippingservice.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.shippingservice.service.port }}  
      targetPort: {{ .Values.shippingservice.service.targetPort }}
  type: {{ .Values.shippingservice.service.type }}
